<?php

declare(strict_types=1);

namespace Certigniter\CertificateRenderer;

use Certigniter\CertificateRenderer\Data\CertificateProject;
use Certigniter\CertificateRenderer\Data\DesignElement;
use Certigniter\CertificateRenderer\Support\ElementOverrides;
use Certigniter\CertificateRenderer\Support\ElementSources;
use Certigniter\CertificateRenderer\Support\FontRegistrar;
use Certigniter\CertificateRenderer\Support\GhostscriptRasterizer;
use Certigniter\CertificateRenderer\Support\GroupComposer;
use Certigniter\CertificateRenderer\Support\IgniterPackage;
use Certigniter\CertificateRenderer\Support\RecipientMerge;
use Certigniter\CertificateRenderer\Support\Units;
use Dompdf\Dompdf;
use Dompdf\Options;
use RuntimeException;

class CertificateRenderer
{
    public const FONT_HEIGHT_RATIO = 1.0;

    /** Design units are CSS pixels (1/96 inch); PDF points are 1/72 inch. */
    public const CANVAS_PX_TO_PDF_PT = 72 / 96;

    /** @var string[] non-fatal issues from the most recent render (e.g. an image that couldn't be resolved server-side) */
    private array $warnings = [];

    /**
     * @param  string  $ghostscriptBinary  executable used by capture() to rasterize a PDF to PNG -
     *                                     shelled out to directly (no `imagick` extension involved)
     */
    public function __construct(
        private readonly string $encryptionKey,
        private readonly bool $composeGroupTransforms,
        private readonly string $ghostscriptBinary = 'gs',
    ) {}

    /**
     * Unpack a .igniter package's raw bytes and render it straight to PDF
     * bytes. This is the one-call entry point most callers want.
     *
     * @param  array<string, string>|null  $recipient  a single row from a
     *                                                 recipient CSV (see RecipientMerge) - null for a static, single-copy
     *                                                 certificate with no merge fields resolved (any variableName/{{token}}
     *                                                 elements render literally empty/unsubstituted).
     * @param  array<string, string>  $imageOverrides  image element ID => raw base64 or data-URI replacement bytes
     * @param  array<string, string>  $qrCodeOverrides  qrcode OR barcode element ID => literal payload to encode
     *                                                  (e.g. a per-recipient verification URL or code generated by
     *                                                  your application) - see DesignElement::isVerificationCode()
     *                                                  and CertificateProject::verificationCodeElementIds()
     */
    public function renderIgniterToPdf(
        string $igniterContents,
        ?array $recipient = null,
        ?string $encryptionKey = null,
        array $imageOverrides = [],
        array $qrCodeOverrides = [],
    ): string {
        $project = $this->parseIgniter($igniterContents, $encryptionKey);

        return $this->renderProjectToPdf($project, $recipient, $imageOverrides, $qrCodeOverrides);
    }

    /**
     * Render an .igniter file straight to a PNG preview image and save it
     * to disk - useful for a quick visual snapshot (e.g. a sample
     * certificate for a demo or landing page). Shells out to a Ghostscript
     * binary directly (see the `certigniter.ghostscript_binary` config
     * value) rather than going through the `imagick` PHP extension, so the
     * only new system requirement is the `gs` executable itself.
     *
     * @param  array<string, string>|null  $recipient  see renderIgniterToPdf()
     * @param  array<string, string>  $imageOverrides  see renderIgniterToPdf()
     * @param  array<string, string>  $qrCodeOverrides  see renderIgniterToPdf()
     * @param  ?string  $outputPath  where to write the PNG; a temp file is created when omitted
     * @param  int  $resolution  rasterization density in DPI - higher looks sharper but is slower/larger
     * @return string the path the PNG was written to (== $outputPath when given)
     */
    public function capture(
        string $igniterContents,
        ?array $recipient = null,
        ?string $encryptionKey = null,
        array $imageOverrides = [],
        array $qrCodeOverrides = [],
        ?string $outputPath = null,
        int $resolution = 150,
    ): string {
        $pdf = $this->renderIgniterToPdf($igniterContents, $recipient, $encryptionKey, $imageOverrides, $qrCodeOverrides);

        return (new GhostscriptRasterizer($this->ghostscriptBinary))->firstPageToPng($pdf, $outputPath ?? tempnam(sys_get_temp_dir(), 'certigniter-thumb-').'.png', $resolution);
    }

    /**
     * Unpack and parse a `.igniter` package without rendering it. Useful for
     * discovering recipient fields and replaceable image element IDs.
     *
     * A `.igniter` is a ZIP container: an AES-encrypted `manifest.json`
     * describing the project, plus the raw image and font bytes it references
     * under `assets/`. See IgniterPackage for the layout and the checks
     * applied to it.
     */
    public function parseIgniter(string $igniterContents, ?string $encryptionKey = null): CertificateProject
    {
        return CertificateProject::fromArray(
            IgniterPackage::decode($igniterContents, $encryptionKey ?? $this->encryptionKey)
        );
    }

    /**
     * @param  array<string, string>|null  $recipient
     * @param  array<string, string>  $imageOverrides  element ID => base64 image bytes
     * @param  array<string, string>  $qrCodeOverrides  qrcode/barcode element ID => literal payload to encode - applied
     *                                                  after recipient merge, so it always wins over both a
     *                                                  static `data` value and any {{token}}/<token> substitution
     */
    public function renderProjectToPdf(
        CertificateProject $project,
        ?array $recipient = null,
        array $imageOverrides = [],
        array $qrCodeOverrides = [],
    ): string {
        $this->warnings = [];

        $elements = GroupComposer::resolve($project, $this->composeGroupTransforms);
        $elements = array_values(array_filter($elements, fn (DesignElement $e) => $e->isVisible()));
        $elements = ElementOverrides::images($elements, $imageOverrides);

        if ($recipient !== null) {
            $elements = array_map(fn (DesignElement $e) => RecipientMerge::apply($e, $recipient, $project), $elements);
        }

        $elements = ElementOverrides::codes($elements, $qrCodeOverrides);

        $sources = new ElementSources;
        $imageSources = $sources->images($elements);
        $codeSources = $sources->codes($elements, $project);
        $this->warnings = $sources->warnings();

        $fontCachePath = sys_get_temp_dir().'/certigniter-dompdf-fonts';
        if (! is_dir($fontCachePath) && ! mkdir($fontCachePath, 0700, true) && ! is_dir($fontCachePath)) {
            throw new RuntimeException("Unable to create the temporary font cache: {$fontCachePath}");
        }
        $fonts = new FontRegistrar($project->embeddedFonts, $fontCachePath);

        $options = new Options;
        $options->setIsRemoteEnabled(false);
        $options->setDefaultFont(FontRegistrar::FALLBACK_FAMILY);
        // Dompdf expands every font's measured line box by 10% by default.
        // A certificate's line spacing is the font's own metrics plus the
        // saved `lineHeight` leading, so the extra 10% would make
        // multi-line text progressively taller than designed.
        $options->setFontHeightRatio(self::FONT_HEIGHT_RATIO);
        $options->setFontDir($fontCachePath);
        $options->setFontCache($fontCachePath);
        $options->setTempDir($fontCachePath);
        // The font cache is the only directory this package reads font files
        // from now that it ships none of its own; Dompdf's own lib/fonts is
        // added so the built-in fallback family stays loadable under chroot.
        $options->setChroot([$fontCachePath, FontRegistrar::builtInFontDirectory($options)]);
        $dompdf = new Dompdf($options);
        $fonts->registerAll($dompdf);

        /** @var view-string $view */
        $view = 'certigniter::certificate';

        $html = view($view, [
            'project' => $project,
            'elements' => $elements,
            'fonts' => $fonts,
            'imageSources' => $imageSources,
            'codeSources' => $codeSources,
        ])->render();

        $dompdf->loadHtml($html);
        // Always pass the *literal* [x1,y1,x2,y2] rect with orientation
        // 'portrait' (dompdf's default) - Dompdf::getPaperSize() swaps
        // width/height whenever orientation is 'landscape', even for an
        // already-explicit custom array, which would double-swap a rect
        // that's already correctly proportioned and silently transpose the
        // page (caught via a real rendered-PDF visual check, not just unit
        // tests: a 200x150mm project was coming out 150x200mm).
        $dompdf->setPaper($this->paperSizePoints($project), 'portrait');
        $dompdf->render();

        return $dompdf->output();
    }

    /** @return string[] */
    public function warnings(): array
    {
        return $this->warnings;
    }

    /** @return array{0: float, 1: float, 2: float, 3: float} dompdf's custom-paper-size shape: [x1, y1, x2, y2] in points */
    private function paperSizePoints(CertificateProject $project): array
    {
        $factor = match (strtolower($project->unit)) {
            'mm' => 2.83464567,
            'cm' => 28.3464567,
            'in' => 72.0,
            default => 1.0, // already points
        };

        return [0, 0, $project->width * $factor, $project->height * $factor];
    }
}
