<?php

namespace Certigniter\CertificateRenderer;

use Certigniter\CertificateRenderer\Data\CertificateProject;
use Certigniter\CertificateRenderer\Data\DesignElement;
use Certigniter\CertificateRenderer\Support\BarcodeRenderer;
use Certigniter\CertificateRenderer\Support\ColorConverter;
use Certigniter\CertificateRenderer\Support\FontRegistrar;
use Certigniter\CertificateRenderer\Support\GroupComposer;
use Certigniter\CertificateRenderer\Support\IgniterPackage;
use Certigniter\CertificateRenderer\Support\QrCodeRenderer;
use Certigniter\CertificateRenderer\Support\RecipientMerge;
use Dompdf\Dompdf;
use Dompdf\Options;
use RuntimeException;
use Throwable;

class CertificateRenderer
{
    public const FONT_HEIGHT_RATIO = 1.0;

    /** Flutter logical pixels are 1/96 inch; PDF points are 1/72 inch. */
    public const CANVAS_PX_TO_PDF_PT = 72 / 96;

    /** @var string[] non-fatal issues from the most recent render (e.g. an image that couldn't be resolved server-side) */
    private array $warnings = [];

    /**
     * @param  string  $ghostscriptBinary  executable used by capture() to rasterize a PDF to PNG -
     *                                     shelled out to directly (no `imagick` extension involved)
     */
    public function __construct(
        private readonly string $encryptionKey,
        private readonly bool $composeGroupTransforms,
        private readonly string $ghostscriptBinary = 'gs',
    ) {}

    /**
     * Unpack a .igniter package's raw bytes and render it straight to PDF
     * bytes. This is the one-call entry point most callers want.
     *
     * @param  array<string, string>|null  $recipient  a single row from a
     *                                                 recipient CSV (see RecipientMerge) - null for a static, single-copy
     *                                                 certificate with no merge fields resolved (any variableName/{{token}}
     *                                                 elements render literally empty/unsubstituted).
     * @param  array<string, string>  $imageOverrides  image element ID => raw base64 or data-URI replacement bytes
     * @param  array<string, string>  $qrCodeOverrides  qrcode OR barcode element ID => literal payload to encode
     *                                                  (e.g. a per-recipient verification URL or code generated by
     *                                                  the host application) - see DesignElement::isVerificationCode()
     *                                                  and CertificateProject::verificationCodeElementIds()
     */
    public function renderIgniterToPdf(
        string $igniterContents,
        ?array $recipient = null,
        ?string $encryptionKey = null,
        array $imageOverrides = [],
        array $qrCodeOverrides = [],
    ): string {
        $project = $this->parseIgniter($igniterContents, $encryptionKey);

        return $this->renderProjectToPdf($project, $recipient, $imageOverrides, $qrCodeOverrides);
    }

    /**
     * Render an .igniter file straight to a PNG preview image and save it
     * to disk - useful for a quick visual snapshot (e.g. a sample
     * certificate for a demo or landing page). Shells out to a Ghostscript
     * binary directly (see the `certigniter.ghostscript_binary` config
     * value) rather than going through the `imagick` PHP extension, so the
     * only new system requirement is the `gs` executable itself.
     *
     * @param  array<string, string>|null  $recipient  see renderIgniterToPdf()
     * @param  array<string, string>  $imageOverrides  see renderIgniterToPdf()
     * @param  array<string, string>  $qrCodeOverrides  see renderIgniterToPdf()
     * @param  ?string  $outputPath  where to write the PNG; a temp file is created when omitted
     * @param  int  $resolution  rasterization density in DPI - higher looks sharper but is slower/larger
     * @return string the path the PNG was written to (== $outputPath when given)
     */
    public function capture(
        string $igniterContents,
        ?array $recipient = null,
        ?string $encryptionKey = null,
        array $imageOverrides = [],
        array $qrCodeOverrides = [],
        ?string $outputPath = null,
        int $resolution = 150,
    ): string {
        $pdf = $this->renderIgniterToPdf($igniterContents, $recipient, $encryptionKey, $imageOverrides, $qrCodeOverrides);

        return $this->pdfToPngThumbnail($pdf, $outputPath ?? tempnam(sys_get_temp_dir(), 'certigniter-thumb-').'.png', $resolution);
    }

    private function pdfToPngThumbnail(string $pdfBytes, string $outputPath, int $resolution): string
    {
        if (! function_exists('proc_open')) {
            throw new RuntimeException('The PHP proc_open() function is disabled - required to shell out to Ghostscript for certificate thumbnails.');
        }

        $directory = dirname($outputPath);
        if (! is_dir($directory) && ! mkdir($directory, 0755, true) && ! is_dir($directory)) {
            throw new RuntimeException("Unable to create the thumbnail directory: {$directory}");
        }

        $tempPdfPath = tempnam(sys_get_temp_dir(), 'certigniter-thumb-src-').'.pdf';
        file_put_contents($tempPdfPath, $pdfBytes);

        try {
            $this->runGhostscript($tempPdfPath, $outputPath, $resolution);
        } finally {
            @unlink($tempPdfPath);
        }

        return $outputPath;
    }

    /**
     * Shells out to Ghostscript directly (an array command, so no shell
     * interpolation/escaping is involved) rather than going through the
     * `imagick` extension, since a bare `gs` binary is a lighter system
     * requirement than compiling/enabling a PHP extension.
     */
    private function runGhostscript(string $pdfPath, string $outputPath, int $resolution): void
    {
        // Suppressed deliberately: a missing binary makes proc_open() raise
        // an E_WARNING ("posix_spawn() failed: No such file or directory")
        // that a booted Laravel app's error handler promotes to an
        // ErrorException before the $process === false check below ever
        // runs, leaking that raw OS-level message instead of the clear one
        // below. The `@` keeps behavior identical whether or not a Laravel
        // error handler is installed (this package also runs standalone).
        $process = @proc_open(
            [
                $this->ghostscriptBinary,
                '-q',
                '-dSAFER',
                '-dBATCH',
                '-dNOPAUSE',
                // Only the first page is rasterized, so a multi-page PDF
                // isn't fully rendered just to preview it.
                '-dFirstPage=1',
                '-dLastPage=1',
                '-dTextAlphaBits=4',
                '-dGraphicsAlphaBits=4',
                '-sDEVICE=pngalpha',
                "-r{$resolution}",
                "-sOutputFile={$outputPath}",
                $pdfPath,
            ],
            [1 => ['pipe', 'w'], 2 => ['pipe', 'w']],
            $pipes,
        );

        if ($process === false) {
            throw new RuntimeException(
                "Unable to start the Ghostscript process ('{$this->ghostscriptBinary}') - is Ghostscript "
                .'installed and on PATH? (e.g. `brew install ghostscript` / `apt-get install ghostscript`). '
                .'Set certigniter.ghostscript_binary / CERTIGNITER_GHOSTSCRIPT_BINARY if it uses a different name or path.'
            );
        }

        $stdout = stream_get_contents($pipes[1]);
        $stderr = stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);
        $exitCode = proc_close($process);

        if ($exitCode !== 0 || ! is_file($outputPath)) {
            throw new RuntimeException(sprintf(
                "Ghostscript ('%s') failed to rasterize the certificate to PNG (exit %d): %s",
                $this->ghostscriptBinary,
                $exitCode,
                trim($stderr."\n".$stdout) ?: 'no output',
            ));
        }
    }

    /**
     * Unpack and parse a `.igniter` package without rendering it. Useful for
     * discovering recipient fields and replaceable image element IDs.
     *
     * A `.igniter` is a ZIP container: an AES-encrypted `manifest.json`
     * describing the project, plus the raw image and font bytes it references
     * under `assets/`. See IgniterPackage for the layout and the checks
     * applied to it.
     */
    public function parseIgniter(string $igniterContents, ?string $encryptionKey = null): CertificateProject
    {
        return CertificateProject::fromArray(
            IgniterPackage::decode($igniterContents, $encryptionKey ?? $this->encryptionKey)
        );
    }

    /**
     * @param  array<string, string>|null  $recipient
     * @param  array<string, string>  $imageOverrides  element ID => base64 image bytes
     * @param  array<string, string>  $qrCodeOverrides  qrcode/barcode element ID => literal payload to encode - applied
     *                                                  after recipient merge, so it always wins over both a
     *                                                  static `data` value and any {{token}}/<token> substitution
     */
    public function renderProjectToPdf(
        CertificateProject $project,
        ?array $recipient = null,
        array $imageOverrides = [],
        array $qrCodeOverrides = [],
    ): string {
        $this->warnings = [];

        $elements = GroupComposer::resolve($project, $this->composeGroupTransforms);
        $elements = array_values(array_filter($elements, fn (DesignElement $e) => $e->isVisible()));
        $elements = $this->applyImageOverrides($elements, $imageOverrides);

        if ($recipient !== null) {
            $elements = array_map(fn (DesignElement $e) => RecipientMerge::apply($e, $recipient, $project), $elements);
        }

        $elements = $this->applyQrCodeOverrides($elements, $qrCodeOverrides);

        $imageSources = $this->resolveImageSources($elements);
        $codeSources = $this->resolveCodeSources($elements, $project);
        $fontCachePath = sys_get_temp_dir().'/certigniter-dompdf-fonts';
        if (! is_dir($fontCachePath) && ! mkdir($fontCachePath, 0700, true) && ! is_dir($fontCachePath)) {
            throw new RuntimeException("Unable to create the temporary font cache: {$fontCachePath}");
        }
        $fonts = new FontRegistrar($project->embeddedFonts, $fontCachePath);

        $options = new Options;
        $options->setIsRemoteEnabled(false);
        $options->setDefaultFont(FontRegistrar::FALLBACK_FAMILY);
        // Dompdf expands every font's measured line box by 10% by default.
        // Certigniter's Flutter and package:pdf renderers use the font's
        // actual metrics and then add only the saved `lineHeight` leading,
        // so Dompdf's default made multi-line text progressively taller.
        $options->setFontHeightRatio(self::FONT_HEIGHT_RATIO);
        $options->setFontDir($fontCachePath);
        $options->setFontCache($fontCachePath);
        $options->setTempDir($fontCachePath);
        // The font cache is the only directory this package reads font files
        // from now that it ships none of its own; Dompdf's own lib/fonts is
        // added so the built-in fallback family stays loadable under chroot.
        $options->setChroot([$fontCachePath, FontRegistrar::builtInFontDirectory($options)]);
        $dompdf = new Dompdf($options);
        $fonts->registerAll($dompdf);

        $html = view('certigniter::certificate', [
            'project' => $project,
            'elements' => $elements,
            'fonts' => $fonts,
            'imageSources' => $imageSources,
            'codeSources' => $codeSources,
        ])->render();

        $dompdf->loadHtml($html);
        // Always pass the *literal* [x1,y1,x2,y2] rect with orientation
        // 'portrait' (dompdf's default) - Dompdf::getPaperSize() swaps
        // width/height whenever orientation is 'landscape', even for an
        // already-explicit custom array, which would double-swap a rect
        // that's already correctly proportioned and silently transpose the
        // page (caught via a real rendered-PDF visual check, not just unit
        // tests: a 200x150mm project was coming out 150x200mm).
        $dompdf->setPaper($this->paperSizePoints($project), 'portrait');
        $dompdf->render();

        return $dompdf->output();
    }

    /**
     * Replace embedded image bytes by stable canvas element ID without
     * mutating the parsed marketplace template object.
     *
     * @param  DesignElement[]  $elements
     * @param  array<string, string>  $overrides
     * @return DesignElement[]
     */
    private function applyImageOverrides(array $elements, array $overrides): array
    {
        if ($overrides === []) {
            return $elements;
        }

        return array_map(function (DesignElement $element) use ($overrides): DesignElement {
            $replacement = $overrides[$element->id] ?? null;
            if ($element->type !== 'image' || ! is_string($replacement) || trim($replacement) === '') {
                return $element;
            }

            $clone = clone $element;
            $clone->properties['imageData'] = preg_replace('#^data:image/[^;]+;base64,#i', '', trim($replacement));
            unset($clone->properties['path']);

            return $clone;
        }, $elements);
    }

    /**
     * Replace a qrcode or barcode element's encoded payload by stable canvas
     * element ID - the mechanism a host application uses to inject a value
     * it generates itself (e.g. a per-recipient verification URL or code)
     * that has no corresponding column in a CSV recipient record. This is
     * the only way to give a "Verification link" code (see
     * DesignElement::isVerificationCode()) any data at all, since the Design
     * Studio always saves that element's `data` as empty. It also works on
     * ordinary "Static"/"Dynamic value" codes, where it simply wins over the
     * static/merged value.
     *
     * @param  DesignElement[]  $elements
     * @param  array<string, string>  $overrides  qrcode/barcode element ID => literal payload
     * @return DesignElement[]
     */
    private function applyQrCodeOverrides(array $elements, array $overrides): array
    {
        if ($overrides === []) {
            return $elements;
        }

        return array_map(function (DesignElement $element) use ($overrides): DesignElement {
            $replacement = $overrides[$element->id] ?? null;
            if (! $element->isCode() || ! is_string($replacement) || $replacement === '') {
                return $element;
            }

            $clone = clone $element;
            $clone->properties['data'] = $replacement;

            return $clone;
        }, $elements);
    }

    /** @return string[] */
    public function warnings(): array
    {
        return $this->warnings;
    }

    /** @param DesignElement[] $elements @return array<string, array{src: string, aspectRatio: ?float}> */
    private function resolveImageSources(array $elements): array
    {
        $sources = [];

        foreach ($elements as $element) {
            if ($element->type !== 'image') {
                continue;
            }

            $imageData = $element->property('imageData');

            if (is_string($imageData) && $imageData !== '') {
                $clean = str_contains($imageData, ',') ? substr($imageData, strpos($imageData, ',') + 1) : $imageData;
                $mime = $this->sniffImageMime($clean) ?? 'image/png';
                $bytes = base64_decode($clean, true);
                $size = $bytes === false ? false : @getimagesizefromstring($bytes);
                $sources[$element->id] = [
                    'src' => "data:{$mime};base64,{$clean}",
                    'aspectRatio' => is_array($size) && $size[1] > 0 ? $size[0] / $size[1] : null,
                ];

                continue;
            }

            $path = $element->property('path');

            if (is_string($path) && $path !== '') {
                $this->warnings[] = sprintf(
                    "Element %s: image only has a local 'path' (%s) from the machine that created it - .igniter "
                    ."files don't carry font/image bytes for 'path'-only images, so this can't be resolved on a "
                    .'server and was skipped. Re-save the project so its images are embedded (imageData), or '
                    .'supply the file yourself.',
                    $element->id,
                    $path,
                );
            }
        }

        return $sources;
    }

    /**
     * QR/barcode generation is precomputed here (rather than inline in the
     * Blade view) specifically so a single malformed element - most often
     * a barcode symbology that rejects characters left over from an
     * unresolved {{token}}/<token> (e.g. Code39 can't encode most of what
     * Code128 can) - degrades to a skip-and-warn instead of aborting the
     * entire render, the same way an unresolvable image does.
     *
     * @param  DesignElement[]  $elements
     * @return array<string, string> element id => data: URI
     */
    private function resolveCodeSources(array $elements, CertificateProject $project): array
    {
        $sources = [];

        foreach ($elements as $element) {
            if (! $element->isCode()) {
                continue;
            }

            $data = (string) $element->property('data', '');
            $unresolved = $this->unresolvedCodeWarning($element, $data);

            if ($unresolved !== null) {
                $this->warnings[] = $unresolved;

                continue;
            }

            $foreground = ColorConverter::toRgba($element->property('color'), $project->colorFormat, '#000000');

            try {
                if ($element->type === 'qrcode') {
                    $background = ColorConverter::toRgba($element->property('backgroundColor'), $project->colorFormat, '#FFFFFF');
                    $sizePx = (int) round(min($element->width, $element->height) * 3.78);

                    $sources[$element->id] = QrCodeRenderer::svgDataUri(
                        $data !== '' ? $data : 'certigniter',
                        $sizePx,
                        $foreground,
                        $background,
                        (int) $element->property('errorCorrectionLevel', 0),
                    );
                } else {
                    $sources[$element->id] = BarcodeRenderer::pngDataUri(
                        $data !== '' ? $data : '123456789',
                        (string) $element->property('barcodeType', 'code128'),
                        (int) round($element->width * 3.78),
                        (int) round($element->height * 3.78),
                        $foreground,
                    );
                }
            } catch (Throwable $e) {
                $this->warnings[] = sprintf(
                    'Element %s (%s): could not generate this code (%s) - it was skipped. This usually means the '
                    .'data contains characters its symbology/format can\'t encode (often a leftover, unresolved '
                    .'{{token}}/<token> when no matching recipient value was supplied).',
                    $element->id,
                    $element->type,
                    $e->getMessage(),
                );
            }
        }

        return $sources;
    }

    /**
     * A "Verification link" or "Dynamic value" code with nothing to encode
     * is skipped rather than rendered with placeholder data - a scannable
     * code that encodes the wrong thing is worse than a missing one.
     */
    private function unresolvedCodeWarning(DesignElement $element, string $data): ?string
    {
        if ($data !== '') {
            return null;
        }

        $label = $element->type === 'qrcode' ? 'QR code' : 'barcode';

        if ($element->isVerificationCode()) {
            return sprintf(
                "Element %s: this %s's content source is 'Verification link' but no value was supplied for it - "
                .'pass its element ID and the value to encode (e.g. a verification URL or code) in '
                .'$qrCodeOverrides. It was skipped.',
                $element->id,
                $label,
            );
        }

        if ($element->isDynamicCode()) {
            $variableName = trim((string) $element->property('variableName', ''));

            return $variableName === ''
                ? sprintf(
                    "Element %s: this %s's content source is 'Dynamic value' but no data column was ever set for it "
                    .'(properties.variableName is empty). It was skipped.',
                    $element->id,
                    $label,
                )
                : sprintf(
                    "Element %s: this %s's content source is 'Dynamic value' bound to column '%s', but the recipient "
                    .'record has no value for it. It was skipped.',
                    $element->id,
                    $label,
                    $variableName,
                );
        }

        return null;
    }

    private function sniffImageMime(string $base64): ?string
    {
        $binary = base64_decode($base64, true);

        if ($binary === false || strlen($binary) < 12) {
            return null;
        }

        return match (true) {
            str_starts_with($binary, "\x89PNG\r\n\x1a\n") => 'image/png',
            str_starts_with($binary, "\xFF\xD8\xFF") => 'image/jpeg',
            str_starts_with($binary, 'GIF87a') || str_starts_with($binary, 'GIF89a') => 'image/gif',
            str_starts_with($binary, 'RIFF') && str_contains(substr($binary, 8, 4), 'WEBP') => 'image/webp',
            default => null,
        };
    }

    /** @return array{0: float, 1: float, 2: float, 3: float} dompdf's custom-paper-size shape: [x1, y1, x2, y2] in points */
    private function paperSizePoints(CertificateProject $project): array
    {
        $factor = match (strtolower($project->unit)) {
            'mm' => 2.83464567,
            'cm' => 28.3464567,
            'in' => 72.0,
            default => 1.0, // already points
        };

        return [0, 0, $project->width * $factor, $project->height * $factor];
    }
}
