<?php

declare(strict_types=1);

namespace Certigniter\CertificateRenderer\Data;

/**
 * One element on a certificate page (text, placeholder_text, image, shape,
 * qrcode, barcode or group). Geometry is typed; `properties` is
 * deliberately a loose bag, because the format adds new keys over time
 * without a schema version, and every reader must tolerate keys it does
 * not know and supply defaults for keys that are absent.
 */
class DesignElement
{
    /**
     * @param  array<string, mixed>  $properties
     * @param  string[]|null  $childrenIds
     */
    public function __construct(
        public string $id,
        public string $type,
        public float $x,
        public float $y,
        public float $width,
        public float $height,
        public array $properties = [],
        public ?array $childrenIds = null,
    ) {}

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            id: (string) ($data['id'] ?? ''),
            type: (string) ($data['type'] ?? ''),
            x: (float) ($data['x'] ?? 0),
            y: (float) ($data['y'] ?? 0),
            width: (float) ($data['width'] ?? 0),
            height: (float) ($data['height'] ?? 0),
            properties: is_array($data['properties'] ?? null) ? $data['properties'] : [],
            childrenIds: isset($data['childrenIds']) && is_array($data['childrenIds'])
                ? array_map('strval', $data['childrenIds'])
                : null,
        );
    }

    public function property(string $key, mixed $default = null): mixed
    {
        return $this->properties[$key] ?? $default;
    }

    public function rotation(): float
    {
        return (float) $this->property('rotation', 0.0);
    }

    public function opacity(): float
    {
        return (float) $this->property('opacity', 1.0);
    }

    public function mirrorHorizontal(): bool
    {
        return $this->property('mirrorHorizontal', false) === true;
    }

    public function mirrorVertical(): bool
    {
        return $this->property('mirrorVertical', false) === true;
    }

    /** Default true: absence of the key means "visible", not "hidden". */
    public function isVisible(): bool
    {
        return $this->property('isVisible', true) !== false;
    }

    /**
     * True for an image element that was generated by AI
     * (`properties.aiGenerated`), as opposed to one that was uploaded or
     * drawn. `aiModel`/`aiPrompt`/`aiGeneratedAt` carry
     * the accompanying attribution and are read directly via property()
     * rather than through dedicated accessors, matching this class's pattern
     * for informational (non-branching) fields.
     */
    public function isAiGenerated(): bool
    {
        return $this->property('aiGenerated', false) === true;
    }

    public function isGroup(): bool
    {
        return $this->type === 'group';
    }

    public function isTextLike(): bool
    {
        return in_array($this->type, ['text', 'placeholder_text', 'dynamic_text'], true);
    }

    /**
     * True for a QR code whose content source is "Verification link"
     * (`qrType: 'verification'`, or the legacy `'authentication'` that older
     * files still carry and which resolves identically). Such an element
     * stores empty `data`: its real payload, typically a per-recipient
     * verification URL, only exists at issue time and must be supplied by
     * the calling application through `qrCodeOverrides`. A project holds at
     * most one of these.
     */
    public function isQrAuthenticationLink(): bool
    {
        return $this->type === 'qrcode' && $this->isVerificationCode();
    }

    /** True for a qrcode or barcode element - the two types whose `data` is encoded rather than drawn. */
    public function isCode(): bool
    {
        return in_array($this->type, ['qrcode', 'barcode'], true);
    }

    /**
     * True for a QR code OR barcode whose content source is "Verification
     * link". Barcodes carry the same `qrType`/`variableName` content-source
     * properties as QR codes, so a barcode can encode a per-recipient
     * verification code supplied through `qrCodeOverrides` exactly as a QR
     * code can.
     */
    public function isVerificationCode(): bool
    {
        return $this->isCode() && in_array($this->property('qrType', 'custom'), ['verification', 'authentication'], true);
    }

    /**
     * True for a QR code OR barcode whose content source is "Dynamic value",
     * bound to one recipient column via `properties.variableName` - see
     * RecipientMerge for how that column is resolved.
     */
    public function isDynamicCode(): bool
    {
        return $this->isCode() && $this->property('qrType', 'custom') === 'dynamic';
    }

    /**
     * True for a QR code whose content source is "Dynamic value": bound to
     * exactly one recipient column named in `properties.variableName`. The
     * format also mirrors that column name into `data` as
     * `{{ variableName }}` for readers that do not recognise
     * `qrType: 'dynamic'`; RecipientMerge resolves
     * `variableName` directly (see isDynamicCode()) and only falls back to
     * that mirrored token when it is empty.
     */
    public function isDynamicQr(): bool
    {
        return $this->type === 'qrcode' && $this->isDynamicCode();
    }

    /**
     * Where the element's content sits within its box: one of nine
     * positions, `topLeft` through `bottomRight`.
     *
     * Older files omit this property. For them, text derives its horizontal
     * position from its paragraph alignment and is vertically centred;
     * every other element is centred in its box.
     */
    public function contentAlignment(): string
    {
        $stored = $this->property('contentAlignment');
        $valid = [
            'topLeft', 'topCenter', 'topRight',
            'centerLeft', 'center', 'centerRight',
            'bottomLeft', 'bottomCenter', 'bottomRight',
        ];

        if (is_string($stored) && in_array($stored, $valid, true)) {
            return $stored;
        }

        if ($this->isTextLike()) {
            return match ($this->property('textAlign', 'left')) {
                'center' => 'center',
                'right' => 'centerRight',
                default => 'centerLeft',
            };
        }

        return 'center';
    }

    /** @return array{0: float, 1: float} Horizontal and vertical factors in the 0..1 range. */
    public function contentAlignmentFactors(): array
    {
        return match ($this->contentAlignment()) {
            'topLeft' => [0.0, 0.0],
            'topCenter' => [0.5, 0.0],
            'topRight' => [1.0, 0.0],
            'centerLeft' => [0.0, 0.5],
            'centerRight' => [1.0, 0.5],
            'bottomLeft' => [0.0, 1.0],
            'bottomCenter' => [0.5, 1.0],
            'bottomRight' => [1.0, 1.0],
            default => [0.5, 0.5],
        };
    }

    public function centerX(): float
    {
        return $this->x + $this->width / 2;
    }

    public function centerY(): float
    {
        return $this->y + $this->height / 2;
    }

    /** A copy with x/y/rotation/opacity overridden - used to apply a group's composed transform onto a child without mutating the original. */
    public function withEffectiveTransform(float $x, float $y, float $rotation, float $opacity): self
    {
        $clone = clone $this;
        $clone->x = $x;
        $clone->y = $y;
        $clone->properties['rotation'] = $rotation;
        $clone->properties['opacity'] = $opacity;

        return $clone;
    }
}
